Guests = ['Anele', 'Ezile', 'Shannon', 'Mamello']
print(f"Hello {Guests[0]}, you're invited to dinner.")
print(f"Hello {Guests[1]}, you're invited to dinner.")
print(f"Hello {Guests[2]}, you're invited to dinner.")
print(f"Hello {Guests[0]} i've found a bigger dinner table")
print(f"Hello {Guests[1]} i've found a bigger dinner table")
print(f"Hello {Guests[2]} i've found a bigger dinner table")
Guests.insert(0, 'Pule')
Guests.insert(3, 'Smith')
Guests.append('Maggs')
print(Guests)
print(f"Hello {Guests[0]} you're invited to dinner")
print(f"Hello {Guests[1]} you're invited to dinner")
print(f"Hello {Guests[2]} you're invited to dinner")
print(f"Hello {Guests[3]} you're invited to dinner")
print(f"Hello {Guests[4]} you're invited to dinner")
print(f"Hello {Guests[5]} you're invited to dinner")
print(f"Hello {Guests[6]} you're invited to dinner")
print("Unfortunately i can only invite two people.")
print(Guests)
Guests.pop(0)
print("Sorry Pule you're no longer invited.")
print(Guests)
Guests.pop(0)
print("Sorry Anele you're no longer invited.")
print(Guests)
Guests.pop(0)
print("Sorry Ezile you're no longer invited.")
print(Guests)
Guests.pop(0)
print("Sorry Smith you're no longer invited.")
print(Guests)
Guests.pop(0)
print("Sorry Shannon you're no longer invited.")
print(Guests)
del Guests[0]
print(Guests)
del Guests[0]
print(Guests)



