-Robots that can take care of the elderly
-Robots that can teach
-Robots that can quickly analyse diseases
-Robots that assemble buildings
-Robots that can identify financial fraud quickly
-Robots that can gaurd countries borders
-Robots that can be used for police purposes
-Robots that can defend us against alien forces/Robots that can monitor our planet from space against threats